services:
  - type: web
    name: bcp-job-list
    runtime: python
    buildCommand: echo "No build needed"
    startCommand: python server.py
    envVars:
      - key: ACCESS_PASSWORD
        sync: false
